WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2466,1617047999
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2536,1617048015
ERROR:main:Exception on /user [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2590,1617049117
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:POST,2256,1617052724
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 60, in set_borough
    mong_obj.setBorough(city_name,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\database.py", line 15, in setBorough
    borough_obj["cityId"]=_city._id
AttributeError: 'dict' object has no attribute '_id'
INFO:restAPI:POST,2025,1617053015
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 61, in set_borough
    mong_obj.setBorough(city_name,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\database.py", line 15, in setBorough
    borough_obj["cityId"]=_city._id
AttributeError: 'dict' object has no attribute '_id'
INFO:restAPI:POST,2384,1617053056
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 61, in set_borough
    mong_obj.setBorough(city_name,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\database.py", line 15, in setBorough
    borough_obj["cityId"]=_city._id
AttributeError: 'dict' object has no attribute '_id'
INFO:restAPI:POST,1981,1617053077
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 61, in set_borough
    mong_obj.setBorough(city_name,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\database.py", line 16, in setBorough
    borough_obj["cityId"]=_city._id
AttributeError: 'dict' object has no attribute '_id'
INFO:restAPI:POST,2236,1617053103
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 61, in set_borough
    mong_obj.setBorough(city_name,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\database.py", line 15, in setBorough
    print("city:",_city._id)
AttributeError: 'dict' object has no attribute '_id'
INFO:restAPI:POST,2247,1617053123
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:POST,2182,1617053155
ERROR:main:Exception on /trabzon/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,1959,1617054001
INFO:kafka.client:Closing idle connection 1001, last active 27470879 ms ago
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2214,1617092184
INFO:restAPI:GET,2846,1617092217
INFO:restAPI:GET,2475,1617092232
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2549,1617092246
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 59, in set_city
    mong_obj.getCity(request.args)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\db_connection.py", line 23, in getCity
    return result
NameError: name 'result' is not defined
INFO:restAPI:GET,2922,1617092397
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2869,1617092450
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2673,1617092520
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2969,1617092587
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 61, in set_city
    return jsonify(response_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
INFO:restAPI:GET,2785,1617092747
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 62, in set_city
    return jsonify(response_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
INFO:restAPI:GET,2898,1617092768
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 63, in set_city
    return jsonify(response_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
INFO:restAPI:GET,2693,1617092794
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 63, in set_city
    js=jsonify(response_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
INFO:restAPI:GET,2478,1617092822
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 64, in set_city
    js=json.dumps(response_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
INFO:restAPI:GET,2636,1617093056
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2574,1617093263
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2721,1617093302
INFO:restAPI:GET,2438,1617094048
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2847,1617094069
INFO:restAPI:GET,2565,1617094086
INFO:restAPI:GET,2521,1617094097
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2828,1617095403
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2704,1617095446
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2851,1617095464
INFO:restAPI:GET,2502,1617095533
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2587,1617095557
INFO:restAPI:GET,2468,1617095579
INFO:restAPI:GET,2723,1617095608
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 84, in set_borough_with_city_name
    result=mong_obj.getBorough(content,city_name)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\db_connection.py", line 30, in getBorough
    args["cityId"]=city["_id"]
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2825,1617095626
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 85, in set_borough_with_city_name
    result=mong_obj.getBorough(content,city_name)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\db_connection.py", line 30, in getBorough
    args["cityId"]=city["_id"]
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2622,1617095643
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2575,1617095704
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 87, in set_borough_with_city_name
    return jsonify(result_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2691,1617095721
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 87, in set_borough_with_city_name
    return jsonify(result_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2991,1617095773
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 87, in set_borough_with_city_name
    return jsonify(result_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2877,1617095822
ERROR:main:Exception on /trabzon/borough [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 87, in set_borough_with_city_name
    js=jsonify(result_json)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2771,1617095877
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2544,1617095909
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/of [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 81, in set_borough_with_city_name
    content["name"]=name
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2496,1617095970
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/of [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 82, in set_borough_with_city_name
    content["name"]=name
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2880,1617096003
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/of [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 82, in set_borough_with_city_name
    content["name"]=name
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2611,1617096018
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2795,1617096077
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2608,1617096293
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2791,1617096318
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2879,1617096348
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2786,1617096476
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2426,1617096496
INFO:restAPI:GET,2578,1617096794
INFO:restAPI:GET,2508,1617096825
INFO:restAPI:GET,2679,1617096846
INFO:restAPI:GET,2804,1617096943
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1900,1617097595
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1815,1617097620
ERROR:main:Exception on /city [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1458,1617097688
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1854,1617097825
ERROR:main:Exception on /city [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1440,1617097844
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1740,1617098359
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1524,1617098486
INFO:restAPI:PUT,1657,1617098512
INFO:restAPI:PUT,1577,1617098533
INFO:restAPI:POST,2400,1617099158
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:DELETE,1054,1617099168
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:DELETE,951,1617099220
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:DELETE,1190,1617099240
ERROR:main:Exception on /rize [DELETE]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2391,1617099277
INFO:restAPI:DELETE,1130,1617099288
ERROR:main:Exception on /rize [DELETE]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2255,1617099329
INFO:restAPI:DELETE,1123,1617099339
INFO:restAPI:POST,2089,1617099368
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:DELETE,1038,1617099379
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2070,1617099406
INFO:restAPI:DELETE,1070,1617099416
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2127,1617099527
INFO:restAPI:DELETE,992,1617099537
WARNING:kafka.client:Unable to send to wakeup socket!
