ERROR:main:Exception on /samsun [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2032,1617121605
ERROR:main:Exception on /samsun/havza [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: set_borough_with_city_name() got an unexpected keyword argument 'name'
INFO:restAPI:POST,2068,1617122564
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /samsun/havza [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: set_borough_with_city_name() got an unexpected keyword argument 'name'
INFO:restAPI:POST,2003,1617122636
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:POST,2389,1617122660
ERROR:main:Exception on /samsun/havza [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1569,1617133460
WARNING:kafka.client:Unable to send to wakeup socket!
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /trabzon/of/update/postakodu/61830 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1763,1617136398
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2285,1617144796
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /city [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2182,1617144894
INFO:restAPI:POST,2214,1617144927
ERROR:main:Exception on /sehir2 [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2944,1617145007
INFO:restAPI:GET,2797,1617145026
INFO:restAPI:GET,2775,1617145050
INFO:restAPI:PUT,1751,1617145118
ERROR:main:Exception on /trabzon [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 86, in set_city
    state=mong_obj.updateCity(args_dict,content)
  File "C:\Users\eyyup\Desktop\kartaca-project\rest\db_connection.py", line 37, in updateCity
    self.cities_col.update(que,new_values)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 3327, in update
    write_concern, collation=collation)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 870, in _update_retryable
    _update, session)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 866, in _update
    retryable_write=retryable_write)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 837, in _update
    _check_write_command_response(result)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\helpers.py", line 226, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\helpers.py", line 208, in _raise_last_write_error
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}, full error: {'index': 0, 'code': 9, 'errmsg': "'$set' is empty. You must specify a field like so: {$set: {<field>: ...}}"}
INFO:restAPI:PUT,1752,1617145183
INFO:restAPI:PUT,1414,1617145261
INFO:restAPI:PUT,1453,1617145295
INFO:restAPI:DELETE,948,1617145378
INFO:restAPI:DELETE,1394,1617145403
INFO:restAPI:POST,2193,1617145433
ERROR:main:Exception on /sehir1 [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /sehir2 [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2271,1617145448
INFO:restAPI:POST,2290,1617145559
ERROR:main:Exception on /sehir1/ilce1 [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2223,1617145646
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1858,1617145733
ERROR:main:Exception on /borough/ilce2 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2195,1617145789
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1786,1617145844
ERROR:main:Exception on /sehir1/ilce2 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,1928,1617145884
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:POST,2124,1617145988
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /sehir2/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,1965,1617146059
INFO:restAPI:PUT,1620,1617146096
ERROR:main:Exception on /sehir2/ilce2 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1892,1617146110
ERROR:main:Exception on /sehir1/ilce2 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:DELETE,1014,1617146150
INFO:restAPI:POST,2096,1617146176
ERROR:main:Exception on /sehir2/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:DELETE,1062,1617146197
INFO:restAPI:POST,2050,1617146218
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2371,1617146281
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:DELETE,1281,1617146345
INFO:restAPI:POST,2319,1617146375
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
ERROR:main:Exception on /sehir1/borough' [GET]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 113, in set_borough_with_city_name
    args_dict=add_value(request.args,["name"],[borough_name])
  File "main.py", line 41, in add_value
    args[entity_name_list[index]]=value_list[index]
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 200, in __setitem__
    is_immutable(self)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 36, in is_immutable
    raise TypeError("%r objects are immutable" % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
INFO:restAPI:GET,2668,1617146381
INFO:restAPI:DELETE,1322,1617146395
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:DELETE,1199,1617146451
INFO:restAPI:POST,1933,1617146518
ERROR:main:Exception on /sehir1/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,1963,1617146523
ERROR:main:Exception on /sehir2/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1535,1617147458
ERROR:main:Exception on /sehir1/ilce2/update/name/ilce3 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1596,1617147511
ERROR:main:Exception on /sehir1/ilce2/update/name/ilce3 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:PUT,1652,1617147532
ERROR:main:Exception on /sehir1/ilce2/update/name/ilce3 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
WARNING:kafka.client:Unable to send to wakeup socket!
ERROR:main:Exception on /sehir1/ilce2/update/name/ilce3 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:PUT,1824,1617147590
INFO:restAPI:PUT,1462,1617147611
ERROR:main:Exception on /sehir2/ilce2/update/name/ilce4 [PUT]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:GET,2635,1617148852
INFO:kafka.client:Closing idle connection 1001, last active 23511007 ms ago
WARNING:kafka.client:Unable to send to wakeup socket!
WARNING:kafka.client:Unable to send to wakeup socket!
INFO:restAPI:GET,2947,1617180530
INFO:restAPI:POST,2289,1617180578
ERROR:main:Exception on /sehir2/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2215,1617180930
ERROR:main:Exception on /sehir2/borough [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:restAPI:POST,2230,1617182874
ERROR:main:Exception on /sehir3 [POST]
Traceback (most recent call last):
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\eyyup\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
